# Default values for satisfy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: docker.io/anapsix/satisfy
  # if both image.tag and image.digest are present
  # digest will be used
  tag: v3.0.4
  digest: sha256:16a818ab03b6a6bd2625dc9b4760f079fbbddfdd1473994593dfae958c6e7e29
  pullPolicy: Always
  pullSecrets: []
    # - secret1
    # - secret2

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  labels: []
    # traffic-type: external
  hosts: []
    # - chart-example.local
  tls: []
  #  - secretName: composer-cert
  #    hosts:
  #      - chart-example.local

terminationGracePeriodSeconds: 15

livenessProbe:
  enabled: true

readinessProbe:
  enabled: true

resources: {}
  # If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 64Mi
  # requests:
  #   cpu: 100m
  #   memory: 64Mi

nodeSelector: {}
tolerations: []
affinity: {}

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 8Gi
  ## A manually managed Persistent Volume and Claim
  ## Requires persistence.enabled: true
  ## If defined, PVC must be created manually before volume will be bound
  # existingClaim:


## Application settings
satisfy:
  repo_name: myrepo
  homepage: http://chart-example.local
  ssh_private_key: ~  # set it via CLI
                      # for example: `--set satisfy.ssh_private_key="$(<~/.ssh/id_rsa)"`
