apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "satisfy.fullname" . }}
  labels:
    app: {{ template "satisfy.name" . }}
    chart: {{ template "satisfy.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "satisfy.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "satisfy.name" . }}
        release: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
{{ toYaml . | indent 8 }}
      {{- end }}
      initContainers:
        - name: init
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          command:
            - /bin/sh
            - -c
            - >
              set -x;
              set -e;
              if [[ -e /app_persist/satis.json ]]; then
                echo >&2 "Existing installation found, moving on..";
                exit 0
              else
                echo >&2 "Seeding new instance..";
                cp -r /app/* /app_persist/;
                chown -R satisfy:satisfy /app_persist;
              fi
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: app-persist
              mountPath: /app_persist
      containers:
        - name: satisfy
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: REPO_NAME
              value: "{{ .Values.satisfy.repo_name }}"
            - name: HOMEPAGE
              value: "{{ .Values.satisfy.homepage }}"
            {{- if .Values.satisfy.ssh_private_key }}
            - name: SSH_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "satisfy.fullname" . }}
                  key: SSH_PRIVATE_KEY
            {{- end }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: /
              port: http
          {{- end }}
          volumeMounts:
            - name: app-persist
              mountPath: /app
{{- with .Values.resources }}
          resources:
{{ toYaml . | indent 12 }}
{{- end }}
      volumes:
        - name: app-persist
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ template "satisfy.fullname" . }}
        {{- else }}
          emptyDir: {}
        {{- end -}}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
