{{- if .Values.satisfy.ssh_private_key }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "satisfy.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "satisfy.name" . }}
    helm.sh/chart: {{ include "satisfy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  SSH_PRIVATE_KEY: {{ .Values.satisfy.ssh_private_key | b64enc }}
{{- end -}}
